OZ-17: Provide a lab order entry form for SENAITE
ozone-his/ozone-config pull request #9
Opened 2022-03-15 14:30 UTC by reagan-meant

2022-04-15 09:54 UTC, Ruhanga reviewed
Hi @reagan-meant, thanks for the PR. Except for a few comments I've added, when addressed would this PR be ready for merging in ?

2022-04-15 09:54 UTC, Ruhanga commented on openmrs_config/ampathforms/blood.json
> +    "description": "desssssss333",
Do you intend to change this to something more descriptive?

2022-04-15 09:54 UTC, Ruhanga commented on openmrs_config/ampathforms/genitalswab.json
> +  "description": "desssssss333",
Same here.

2022-04-15 09:54 UTC, Ruhanga commented on openmrs_config/ampathforms/skin.json
> +  "description": "desssssss333",
Same here.

2022-04-15 09:54 UTC, Ruhanga commented on openmrs_config/ampathforms/sputum.json
> +  "description": "desssssss333",
Same here.

2022-04-15 09:54 UTC, Ruhanga commented on openmrs_config/ampathforms/stool.json
> +  "description": "desssssss333",
Same here.

2022-04-15 09:54 UTC, Ruhanga commented on openmrs_config/ampathforms/urine.json
> +  "description": "desssssss333",
Same here.

2022-04-28 16:57 UTC, mks-d requested changes
@reagan-meant let's operate a separation of concerns as described here: https://issues.openmrs.org/browse/O3-858?focusedCommentId=283706&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-283706

2022-10-14 09:49 UTC, closed without merging